language: node_js
node_js:
  - "stable"
sudo: false
cache:
  directories:
  - node_modules
install:
  - cd ./client && npm install && cd ..
script:
  - cd ./client && npm test && cd ..
  - cd ./client && npm run build && cd ..
notifications:
  slack: thejuandys:5scN0mDB9GwtbWxG4aevTrQr
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: 1/a6fBTe3vJ9jJBKbFEix8TO-dTdonsMu0U0hgJvXlkt4