const actionTypes = {
    READ_FIREBASE_STORE_REQUESTED : 'READ_FIREBASE_STORE_REQUESTED',
    READ_FIREBASE_STORE_REJECTED  : 'READ_FIREBASE_STORE_REJECTED',
    READ_FIREBASE_STORE_FULFILLED : 'READ_FIREBASE_STORE_FULFILLED',

    UPDATE_FIREBASE_STORE_REQUESTED : 'UPDATE_FIREBASE_STORE_REQUESTED',
    UPDATE_FIREBASE_STORE_REJECTED  : 'UPDATE_FIREBASE_STORE_REJECTED',
    UPDATE_FIREBASE_STORE_FULFILLED : 'UPDATE_FIREBASE_STORE_FULFILLED'
};

export default actionTypes;